import { createHash, randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { env } from '../../config/env.js';

/**
 * Generated audio on the local filesystem.
 *
 * Audio is never stored in MongoDB (DECISIONS.md) - a 16-bit WAV of a paragraph
 * is comfortably past the 16 MB document ceiling, and even under it, pulling
 * binary through the driver on every history query would be slow for no reason.
 *
 * This is a development and single-instance answer. Render's disk is ephemeral,
 * so a deploy wipes it, and two instances would not see each other's files. The
 * fix is an S3-compatible adapter behind this same interface; the key is opaque
 * on purpose so nothing above this file has to change when that lands.
 */
const serverRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const baseDir = path.resolve(serverRoot, env.GENERATED_AUDIO_DIR);

/**
 * Rejects anything that would escape the audio directory.
 *
 * Keys are generated by buildKey below, so this should never fire - but a stored
 * key is read back from the database, and treating a database value as a trusted
 * path is how directory traversal happens.
 */
function resolveKey(key) {
  const resolved = path.resolve(baseDir, key);

  if (resolved !== baseDir && !resolved.startsWith(baseDir + path.sep)) {
    throw new Error('Refusing to resolve a storage key outside the audio directory');
  }

  return resolved;
}

/**
 * Builds a storage key: <userHash>/<uuid>.<ext>
 *
 * Sharded by a hash of the user id rather than the id itself, so a directory
 * listing on the host does not enumerate account identifiers. The uuid means two
 * generations never collide, including retries of the same text.
 */
export function buildKey({ userId, extension }) {
  const shard = createHash('sha256').update(String(userId)).digest('hex').slice(0, 8);
  return `${shard}/${randomUUID()}.${extension}`;
}

export async function put(key, buffer) {
  const target = resolveKey(key);

  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, buffer);

  return { key, byteSize: buffer.byteLength };
}

/** Returns the bytes, or null when the file is gone (an ephemeral disk, usually). */
export async function get(key) {
  try {
    return await fs.readFile(resolveKey(key));
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

/** Best-effort delete. A missing file is already the desired state. */
export async function remove(key) {
  try {
    await fs.unlink(resolveKey(key));
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
}

export function describe() {
  return `local (${path.relative(serverRoot, baseDir)})`;
}
